import { useState } from 'react';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * ExportButton Component
 * 
 * Exports SWOT analysis results as a PDF file
 * 
 * Props:
 *   - swotData: object - The SWOT analysis data to export
 *   - idea: string - The business idea being analyzed
 *   - focusArea: string - The focus area for the analysis
 *   - disabled: boolean - Whether button is disabled
 */
export default function ExportButton({ swotData, idea, focusArea, disabled = false }) {
  const [isExporting, setIsExporting] = useState(false);
  const [error, setError] = useState('');

  const exportToPDF = async () => {
    if (!swotData) {
      setError('No SWOT data to export');
      return;
    }

    setIsExporting(true);
    setError('');

    try {
      // Create a temporary container for the PDF content
      const container = document.createElement('div');
      container.style.position = 'absolute';
      container.style.left = '-9999px';
      container.style.width = '800px';
      container.style.padding = '40px';
      container.style.backgroundColor = 'white';
      container.style.fontFamily = 'Arial, sans-serif';

      // Build the HTML content for the PDF
      container.innerHTML = `
        <div style="text-align: center; margin-bottom: 30px;">
          <h1 style="color: #1f2937; margin: 0 0 10px 0; font-size: 28px;">💡 SWOT Analysis</h1>
          <p style="color: #6b7280; margin: 0; font-size: 14px;">Idea SWOT Generator</p>
        </div>

        <div style="margin-bottom: 25px; padding: 15px; background-color: #f3f4f6; border-radius: 8px;">
          <p style="color: #6b7280; margin: 0 0 5px 0; font-size: 12px; font-weight: bold;">BUSINESS IDEA</p>
          <p style="color: #1f2937; margin: 0 0 10px 0; font-size: 16px; font-weight: bold;">${escapeHtml(idea)}</p>
          <p style="color: #6b7280; margin: 0 0 5px 0; font-size: 12px; font-weight: bold;">FOCUS AREA</p>
          <p style="color: #1f2937; margin: 0; font-size: 14px;">${escapeHtml(focusArea)}</p>
        </div>

        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px;">
          <!-- Strengths -->
          <div style="padding: 15px; border: 2px solid #10b981; border-radius: 8px;">
            <h2 style="color: #10b981; margin: 0 0 10px 0; font-size: 18px;">✓ Strengths</h2>
            <ul style="margin: 0; padding-left: 20px; color: #374151; font-size: 13px;">
              ${(swotData.Strengths || []).map(item => `<li style="margin-bottom: 5px;">${escapeHtml(item)}</li>`).join('')}
            </ul>
          </div>

          <!-- Weaknesses -->
          <div style="padding: 15px; border: 2px solid #ef4444; border-radius: 8px;">
            <h2 style="color: #ef4444; margin: 0 0 10px 0; font-size: 18px;">✗ Weaknesses</h2>
            <ul style="margin: 0; padding-left: 20px; color: #374151; font-size: 13px;">
              ${(swotData.Weaknesses || []).map(item => `<li style="margin-bottom: 5px;">${escapeHtml(item)}</li>`).join('')}
            </ul>
          </div>

          <!-- Opportunities -->
          <div style="padding: 15px; border: 2px solid #3b82f6; border-radius: 8px;">
            <h2 style="color: #3b82f6; margin: 0 0 10px 0; font-size: 18px;">◆ Opportunities</h2>
            <ul style="margin: 0; padding-left: 20px; color: #374151; font-size: 13px;">
              ${(swotData.Opportunities || []).map(item => `<li style="margin-bottom: 5px;">${escapeHtml(item)}</li>`).join('')}
            </ul>
          </div>

          <!-- Threats -->
          <div style="padding: 15px; border: 2px solid #f59e0b; border-radius: 8px;">
            <h2 style="color: #f59e0b; margin: 0 0 10px 0; font-size: 18px;">⚠ Threats</h2>
            <ul style="margin: 0; padding-left: 20px; color: #374151; font-size: 13px;">
              ${(swotData.Threats || []).map(item => `<li style="margin-bottom: 5px;">${escapeHtml(item)}</li>`).join('')}
            </ul>
          </div>
        </div>

        <!-- Niche Score -->
        <div style="padding: 15px; background-color: #f0f9ff; border: 2px solid #0ea5e9; border-radius: 8px; text-align: center;">
          <p style="color: #0369a1; margin: 0 0 5px 0; font-size: 12px; font-weight: bold;">MARKET VIABILITY SCORE</p>
          <p style="color: #0369a1; margin: 0; font-size: 32px; font-weight: bold;">${swotData.NicheScore || 0}/100</p>
        </div>

        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; text-align: center;">
          <p style="color: #9ca3af; margin: 0; font-size: 11px;">
            Generated by Idea SWOT Generator • ${new Date().toLocaleDateString()}
          </p>
        </div>
      `;

      document.body.appendChild(container);

      // Convert HTML to canvas
      const canvas = await html2canvas(container, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });

      // Remove temporary container
      document.body.removeChild(container);

      // Create PDF
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      const imgData = canvas.toDataURL('image/png');
      const imgWidth = 210; // A4 width in mm
      const imgHeight = (canvas.height * imgWidth) / canvas.width;

      pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight);

      // Generate filename with timestamp
      const timestamp = new Date().toISOString().slice(0, 10);
      const filename = `SWOT-Analysis-${timestamp}.pdf`;

      // Download PDF
      pdf.save(filename);

      setIsExporting(false);
    } catch (err) {
      console.error('Export error:', err);
      setError('Failed to export PDF. Please try again.');
      setIsExporting(false);
    }
  };

  return (
    <div>
      <button
        onClick={exportToPDF}
        disabled={disabled || isExporting || !swotData}
        className={`px-4 py-2 rounded-lg font-semibold transition flex items-center gap-2 ${
          disabled || isExporting || !swotData
            ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
            : 'bg-green-600 hover:bg-green-700 text-white cursor-pointer'
        }`}
      >
        {isExporting ? (
          <>
            <span className="inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin"></span>
            Exporting...
          </>
        ) : (
          <>
            📥 Export as PDF
          </>
        )}
      </button>
      {error && (
        <p className="text-red-600 text-sm mt-2">{error}</p>
      )}
    </div>
  );
}

/**
 * Escape HTML special characters to prevent XSS
 */
function escapeHtml(text) {
  if (!text) return '';
  const map = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  };
  return text.replace(/[&<>"']/g, (m) => map[m]);
}

